# This is a basic workflow to help you get started with Actions

name: Build and Test

on:
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build
        run: ./gradlew build --info

      - name: Gradle Dependency Submission
        if: github.ref == 'refs/heads/master'
        continue-on-error: true
        uses: mikepenz/gradle-dependency-submission@v0.8.4

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          # Artifact name
          name: MakeUnbreakableCommand
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            build/libs/MakeUnbreakableCommand-**.jar
